using System;
using System.IO;
using System.Text;
using Umbraco.Cms.Core.Packaging;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Extensions;

namespace Umbraco.Cms.Infrastructure.Packaging
{
    public class PackageCompilationService : IPackageCompilationService
    {
        private RoslynCompiler _roslynCompiler;

        private RoslynCompiler RoslynCompiler
        {
            get
            {
                if (_roslynCompiler is not null)
                {
                    return _roslynCompiler;
                }

                _roslynCompiler = new RoslynCompiler();
                return _roslynCompiler;
            }
        }

        /// <inheritdoc />
        public Stream CreateCompiledPackage(PackageDefinition packageDefinition)
        {
            var packageName = packageDefinition.Name;
            var fileName = Path.GetFileName(packageDefinition.PackagePath);
            // TODO: Get Version string from package definition.
            var migrationCode = GenerateDefaultMigrationCode(packageName, "1.0.0.0");
            FileStream packageXml = File.OpenRead(packageDefinition.PackagePath);

            return RoslynCompiler.CompilePackage(packageName, fileName, packageXml, migrationCode);
        }

        private string GenerateDefaultMigrationCode(string packageName, string versionString)
        {
            var builder = new StringBuilder();
            var packageNamespace = packageName.CleanStringForNamespace();
            if (string.IsNullOrWhiteSpace(packageNamespace))
            {
                packageNamespace = ("BackOfficeAutoGenerated." + Guid.NewGuid()).CleanStringForNamespace();
            }

            // Using statements
            builder.AppendLine("using System.Runtime.Versioning;");
            builder.AppendLine("using Umbraco.Cms.Infrastructure.Packaging;");

            // Add Netstandard assembly property
            builder.AppendLine("[assembly: TargetFramework(\".NETStandard,Version=v2.0\", FrameworkDisplayName = \"\")]");
            // Add Assembly version
            builder.Append("[assembly:System.Reflection.AssemblyVersion(\"");
            builder.Append(versionString);
            builder.AppendLine("\")]");

            // Namespace
            builder.Append("namespace ");
            builder.AppendLine(packageNamespace);
            builder.AppendLine("{");

            // Class definition
            builder.Append("public class DefaultMigration : ");
            builder.AppendLine("AutomaticPackageMigrationPlan {");

            // Constructor
            builder.Append("public DefaultMigration() : base(\"");
            builder.AppendLine($"{packageName}\")");
            builder.AppendLine("{}");

            // Close the brackets.
            builder.AppendLine("}}");

            return builder.ToString();
        }

    }
}
